version: "3.8"

services:
  # Frontend React Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        VITE_API_BASE_URL: /api/v1
        VERCEL: 1
        DOCKER: 1
        BACKEND_ORIGIN: http://host.docker.internal:8080
    container_name: ai-content-frontend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - BACKEND_ORIGIN=http://host.docker.internal:8080
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - ai-content-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
networks:
  ai-content-net:
    external: true
