version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://auth-service:8081/api
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - ai-content-net

networks:
  ai-content-net:
    external: true
