services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      # API URL will be handled by your external API gateway
      REACT_APP_API_URL: /api
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - ai-content-net

networks:
  ai-content-net:
    external: true
