# Development override for docker-compose
# This file is automatically loaded by docker-compose for development

services:
  frontend:
    build:
      target: builder
    command: npm run dev
    ports:
      - "5173:5173"  # Vite dev server port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8081/api/v1
      - VITE_REALTIME_SERVER_URL=http://localhost:3001
    restart: "no"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    read_only: false
    tmpfs: []