services:
  # Frontend React Application (Development Mode)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
        VITE_API_BASE_URL: /api/v1
        DOCKER: 1
    container_name: ai-content-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DOCKER=1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    networks:
      - ai-content-net
    restart: unless-stopped

networks:
  ai-content-net:
    driver: bridge