services:
  # Frontend React Application (Development Mode)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
        VITE_API_BASE_URL: /api/v1
        VERCEL: 1
        DOCKER: 1
        BACKEND_ORIGIN: http://auth-service:8081
    container_name: ai-content-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BACKEND_ORIGIN=http://auth-service:8081
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs/nginx:/var/log/nginx
    networks:
      - ai-content-net
    restart: unless-stopped
networks:
  ai-content-net:
    external: true
